### ISSUE TITLE
Port elCID@UCH tests to Lab

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-lab#29]
Including: 

- [x] Names
- [x] Fields
- [x] Observation choices
- [x] Defauls

**Comment by davidmiller** [comment]
- [ ] Implement in UCLP TB

**Comment by fredkingham** [comment]
This is done on https://elcid-lab-test.herokuapp.com/, I did it in elcid, although in its own module (elcid-labs).

Its implemented in the episode detail view for inpatients at the moment

Defaults still need to be done

**Comment by fredkingham** [comment]
complete on https://elcid-lab-test.herokuapp.com/, lab tests are on the detail view.

also... `labs-in-elcid`
