### ISSUE TITLE
Update for Opal 0.10.0 compatibility

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal-lab#41]
### updating opal-lab
- [x] create a new version of opal-labs 
- [x] change the default version of opal-labs

#### On a new branch
- [x] change the requirements.txt
- [x] update the urls and requirements into the django 10 format [e.g.]https://github.com/openhealthcare/opal-observations/pull/40/files)
- [x] changelog
- [x] make sure tests run on opal 10
- [x] create a pull request

**Comment by fredkingham** [comment]
https://github.com/openhealthcare/opal/blob/v0.10.0/doc/docs/reference/upgrading.md

**Comment by pacharanero** [comment]
I don't appear to have the permissions to do admin-y things like change the default version on GH :-)

**Comment by pacharanero** [comment]
I've pushed a v.0.4.0 branch so if someone else can do this it's fine, or give me permissions and I'll do it; happy either way.
